# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.



## Filtros e np.where()

A função `np.where()` é muito útil para fazer uma seleção condicional de elementos de um array. Por exemplo, em uma empresa, você pode querer identificar quais funcionários têm salários acima da média.


In [1]:
import numpy as np

# Salários dos funcionários
salarios = np.array([3000, 3500, 4000, 2000, 4500, 4000, 5000])

# Calcular a média salarial
media_salarial = np.mean(salarios)

print(f"Média de salários: R$ {media_salarial:.2f}")
# Média de salários: R$ 3714.29

Média de salários: R$ 3714.29


In [ ]:
# Identificar funcionários com salários acima da média
# se fosse uma lista padrão, teria que percorrer a lista
# e para cada elemento perguntar: é acima da média?
# com a função where isso fica mais simples
funcionarios_acima_media = np.where(salarios > media_salarial)
print(funcionarios_acima_media) # printa as posições onde é acima da média
# (array([2, 4, 5, 6]),)

# para mostrar os valores dos salários acima da média
print(salarios[funcionarios_acima_media])
# [4000 4500 4000 5000]

# a linha abaixo imprime mesma saída do print acima
print(salarios[salarios > media_salarial])
# [4000 4500 4000 5000]

(array([2, 4, 5, 6]),)
[4000 4500 4000 5000]
[4000 4500 4000 5000]


In [ ]:
# exibe salários iguais ou maiores que 4000
print(salarios[salarios >= 4000])
# [4000 4500 4000 5000]

[4000 4500 4000 5000]


In [ ]:
# exibe uma mensagem para cada salário
# se for acima, exibe acima da média
# caso contrário, exibe abaixo da média
print(np.where(salarios > media_salarial, "Acima da média", "Abaixo da média"))
# ['Abaixo da média' 'Abaixo da média' 'Acima da média' 'Abaixo da média' 'Acima da média' 'Acima da média' 'Acima da média']

# é como se fosse um for, percorrendo todos os elementos 
# e perguntando algo para cada elemento

['Abaixo da média' 'Abaixo da média' 'Acima da média' 'Abaixo da média'
 'Acima da média' 'Acima da média' 'Acima da média']


In [16]:
# dar bônus de 10% para os funcionários com salários abaixo da média
salarios_bonus = np.where(salarios < media_salarial, (salarios * 1.1), salarios)
print(salarios)
print(salarios_bonus)

[3000 3500 4000 2000 4500 4000 5000]
[3300. 3850. 4000. 2200. 4500. 4000. 5000.]


In [ ]:
# filtrar os salários entre 3000 e 4500 com where

# tentei fazer, mas deu erro
# print(np.where(salarios >= 3000 and salarios <= 3500))
# eu escolhi 3500 de propósito, para ver uma saída diferente do vídeo
# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# fazendo de acordo com o vídeo
# errei o operador, usei and, mas aqui é &
print(np.where((salarios >= 3000) & (salarios <= 4500)))

(array([0, 1, 2, 4, 5]),)


In [20]:
# ajustando salários da faixa acima
salarios_ajustados = np.where((salarios >= 3000) & (salarios <= 4500), salarios * 1.05, salarios)
print(salarios)
print(salarios_ajustados)

[3000 3500 4000 2000 4500 4000 5000]
[3150. 3675. 4200. 2000. 4725. 4200. 5000.]


In [ ]:
# filtrar os salários abaixo de 3000 ou acima de 4500 com where
print(np.where((salarios_ajustados < 3000) | (salarios_ajustados > 4500)))
# (array([3, 4, 6]),)

(array([3, 4, 6]),)


In [24]:
salarios_segundo_ajuste = np.where((salarios_ajustados < 3000) | (salarios_ajustados > 4500), salarios_ajustados * 1.1, salarios_ajustados)
print(salarios_segundo_ajuste)

[3150.  3675.  4200.  2200.  5197.5 4200.  5500. ]
