# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.



## Aplicações do dia a dia

Vamos supor que você trabalha em uma empresa de vendas e tem os preços de diferentes produtos em uma lista. Você quer aumentar o preço de todos os produtos em 10%. Com NumPy, isso é simples.



In [ ]:
import numpy as np

# Preços dos produtos
precos = np.array([20, 25, 30, 35, 40])

# Aumentar os preços em 10 % (ex.: ajuste de inflação)
novos_precos = precos * 1.1

print(novos_precos)
# preços ajustados em 10%
# [22.  27.5 33.  38.5 44. ]

[22.  27.5 33.  38.5 44. ]


## np.sum()

NumPy vem com muitas funções úteis. Por exemplo, você pode usar a função `sum()` para somar todos os elementos de um array. Isso pode ser útil para somar todas as vendas de um dia, por exemplo.



In [ ]:
import numpy as np

# Vendas do dia
vendas = np.array([200, 220, 250, 210, 300])

# Somar todas as vendas
soma_vendas = np.sum(vendas )
print(soma_vendas)
# 1180

1180


## np.mean()

A função `mean()` é usada para calcular a média de um array. Por exemplo, se você quiser calcular a média de vendas diárias em uma semana.


In [ ]:
import numpy as np

# Vendas diárias em uma semana
vendas = np.array([200, 220, 250, 210, 300, 280, 230])

# Calcular a média de vendas
# tentei rodar sem passar o parâmetro esperado, deu erro
# TypeError: mean() missing 1 required positional argument: 'a'
# print(np.mean())

# agora sim, corrigindo
print(np.mean(vendas))
# 241.42857142857142

# formatando com 2 casas decimais
# jeito errado que tentei fazer sem consultar, apenas com o que lembro
# print(f"{np.mean(vendas)}.:2f")
# 241.42857142857142.:2f

# jeito certo
print(f"A média de vendas foi R$: {np.mean(vendas):.2f}")
# A média de vendas foi R$: 241.43

241.42857142857142
A média de vendas foi R$: 241.43


## np.max() e np.min()

As funções `max()` e `min()` são usadas para encontrar o valor máximo e mínimo em um array, respectivamente. Por exemplo, para encontrar o produto mais caro e mais barato.



In [ ]:
import numpy as np

# Preços dos produtos
precos = np.array([20, 25, 30, 35, 40])

# Encontrar o produto mais caro e mais barato
produto_mais_caro = np.max(precos)
produto_mais_barato = np.min(precos)

print(f"Produto mais caro custa R$ {produto_mais_caro:.2f}")
print(f"Produto mais barato custa R$ {produto_mais_barato:.2f}")
# Produto mais caro custa R$ 40.00
# Produto mais barato custa R$ 20.00

Produto mais caro custa R$ 40.00
Produto mais barato custa R$ 20.00


## np.sort()

A função `sort()` é usada para ordenar os elementos de um array. Por exemplo, para ordenar as vendas diárias.



In [19]:
import numpy as np

# Vendas diárias
vendas = np.array([200, 300, 220, 250, 210])

# Ordenar as vendas
vendas_ordenadas = np.sort(vendas)

print("Array fora de ordem")
print(vendas)
print("Array ordenado")
print(vendas_ordenadas)

# [200 300 220 250 210]
# [200 210 220 250 300]

Array fora de ordem
[200 300 220 250 210]
Array ordenado
[200 210 220 250 300]


## np.dot()

A função `np.dot()` é usada para calcular o produto escalar de dois arrays. Por exemplo, em uma empresa de varejo, você pode querer calcular o valor total de vendas, dado o número de cada produto vendido e o preço de cada produto.


In [8]:
import numpy as np

# Número de produtos vendidos - quantidade em unidades
quantidades = np.array([10, 20, 30, 40])

# Preços dos produtos - valor em R$
precos = np.array([5, 10, 15, 20])

# Calcular o valor total de vendas?

In [ ]:
# fazendo a operação por etapas: 
# primeiro, multiplicando um array pelo outro, 
# para saber quanto vendeu de cada produto
total_por_produto = quantidades * precos
print(total_por_produto)
# [ 50 200 450 800]
# cada elemento desse novo array é o produto entre os elementos dos anteriores

[ 50 200 450 800]


In [ ]:
total_vendas = np.sum(total_por_produto)
print(total_vendas)
# 1500
# temos o resultado, mas foi feito em duas etapas

1500


In [ ]:
# fazendo a operação em uma etapa, 
# com método dot()

total_vendas2 = np.dot(quantidades, precos)
print(total_vendas2)
# 1500

1500
