## Exercício

Você é um gerente de vendas e tem os dados de vendas de três produtos diferentes (Produto A, Produto B, Produto C) para os últimos 5 dias em um array 2D NumPy. Cada linha do array representa um produto e cada coluna representa um dia. Seu trabalho é calcular as vendas totais para cada produto e para cada dia.

Use o seguinte array para sua análise:

```python
vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])
```

**Solução:**


In [ ]:
import numpy as np

vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])

vendas_produto = np.sum(vendas, axis=1)
print(vendas_produto)
# [325 433 368]

total_produto_a = vendas_produto[0]
total_produto_b = vendas_produto[1]
total_produto_c = vendas_produto[2]


print(f"Total vendas produto A: R$ {total_produto_a:.2f}")
print(f"Total vendas produto B: R$ {total_produto_b:.2f}")
print(f"Total vendas produto C: R$ {total_produto_c:.2f}")

# Total vendas produto A: R$ 325.00
# Total vendas produto B: R$ 433.00
# Total vendas produto C: R$ 368.00


# vendas por produto eu consegui completo
# vendas por dia, não consegui
# precisei ver a solução
# entendi a solução quando vi, 
# mas não consegui elaborar, preciso praticar mais

vendas_dia = np.sum(vendas, axis=0)
print(vendas_dia)

# [207 225 216 234 244]

# essa parte da soma, ok
# essa parte do for que precisei consultar
for i in range(5):
  print(f"Vendas para o dia {i + 1}: R$ {vendas_dia[i]:.2f}")

# Vendas para o dia 1: R$ 207.00
# Vendas para o dia 2: R$ 225.00
# Vendas para o dia 3: R$ 216.00
# Vendas para o dia 4: R$ 234.00
# Vendas para o dia 5: R$ 244.00

[325 433 368]
Total vendas produto A: R$ 325.00
Total vendas produto B: R$ 433.00
Total vendas produto C: R$ 368.00
[207 225 216 234 244]
Vendas para o dia 1: R$ 207.00
Vendas para o dia 2: R$ 225.00
Vendas para o dia 3: R$ 216.00
Vendas para o dia 4: R$ 234.00
Vendas para o dia 5: R$ 244.00
